---
title: "Bangladesh Summary Statistics"
author: "Piper Zimmerman"
date: "May 25, 2023"
output: pdf_document
---


```{r setup, include=FALSE, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.pos = 'H', fig.height = 3, out.width="\\textwidth", warning = FALSE)
library(psych)
library(knitr)
library(stargazer)
library(tidyverse)
library(dplyr)
library(fpp3)
library(gridExtra) 
library(GGally)
library(readxl)
library(haven)
library(foreign)
library(epiDisplay)
```

* Choose directory

```{r, echo=TRUE}
data <- read_dta("BIHS2018-19.dta")
attach(data)
head(data)
```

#Summary Statistics: Division
```{r, echo=TRUE}
table(data$div_name)
```

```{r}
data$division <- as.factor(div_name)
```


```{r, echo=TRUE}
data_mem <- read_dta("BIHS2018-19Members.dta")
attach(data_mem)
head(data_mem)
```

#Summary Statistics: Gender
```{r, echo=TRUE}
table(data_mem$b1_01)
tab1(data_mem$b1_01, sort.group = "decreasing", cum.percent = TRUE,graph=FALSE)
female<-data_mem[which(data_mem$b1_01==2),]
male<-data_mem[which(data_mem$b1_01==1),]
```

#Summary Statistics: Age
```{r}
describe(data_mem$b1_02)
hist(female$b1_02)
hist(male$b1_02)
```


```{r}
#Farming
farm.codes<-c(64:72)
farming<-data_mem |> mutate(farmer=ifelse(b1_10 %in% farm.codes,1,0))
farming.male<-male|> mutate(farmer=ifelse(b1_10 %in% farm.codes,1,0))
farming.female<-female|> mutate(farmer=ifelse(b1_10 %in% farm.codes,1,0))
sum(farming$farmer)/length(farming$farmer)
sum(farming.male$farmer)/length(farming.male$farmer)
sum(farming.female$farmer)/length(farming.female$farmer)
#Age by gender
data_mem |> group_by(b1_01) |> summarize(meanage=mean(b1_02))
#Houses with children under 2/5
newdat2<-data_mem |> group_by(a01) |> count(b1_02<=2)
sum(newdat2[,2])
newdat5<-data_mem |> group_by(a01) |> count(b1_02<=5)
sum(newdat5[,2])
#Household size
house.size<-data_mem |> group_by(a01) |> summarize(count=n())
house.size.df<-as.data.frame(house.size)
mean(house.size.df$count)
hist(house.size.df$count)
```

```{r}
#By division
data_mem |> group_by(div_name,b1_01) |> summarize(mean.age=mean(b1_02))
data_mem |> ggplot(aes(b1_02))+geom_histogram()+facet_grid(~div_name)+labs(x="Age")
as.data.frame(data_mem |> group_by(div_name,a01) |> summarize(count=n())) |> ggplot(aes(count))+geom_histogram(aes(fill=div_name))+facet_grid(~div_name)+labs(x="Household Size")
```

